<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit47a4c5c435db2e217b6f1ef1b2ca6284
{
    public static $prefixLengthsPsr4 = array (
        'Z' => 
        array (
            'Zalo\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Zalo\\' => 
        array (
            0 => __DIR__ . '/..' . '/zaloplatform/zalo-php-sdk/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit47a4c5c435db2e217b6f1ef1b2ca6284::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit47a4c5c435db2e217b6f1ef1b2ca6284::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit47a4c5c435db2e217b6f1ef1b2ca6284::$classMap;

        }, null, ClassLoader::class);
    }
}
